// Building catalogue, extracted from protected/game.html.
// valid() closures read grid/terrain via the map module so this stays pure
// data plus placement rules, with no rendering or economy logic.

import { grid, nearTerrain, nearBuilding } from './map.js';

export const BUILDINGS = [
 {id:'house', name:"House", ic:'🏠', cat:'Housing', cost:{wood:20,stone:10}, workers:0, popCap:4,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain)},
 {id:'farmerhut', name:"Farmer's Hut", ic:'🧑‍🌾', cat:'Housing', cost:{wood:20}, workers:2, popCap:2,
   valid:(x,y)=>grid[y][x].terrain==='grass',
   desc:'Boosts nearby fields'},
 {id:'fisherhut', name:"Fisherman's Hut", ic:'🎣', cat:'Housing', cost:{wood:20}, workers:2, popCap:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearTerrain(x,y,['sea','river'],1),
   produce:{fish:1.6}},
 {id:'fields', name:"Field", ic:'🌾', cat:'Production', cost:{wood:10}, workers:2, requiresTech:'irrigation',
   valid:(x,y)=>grid[y][x].terrain==='grass', isField:true},
 {id:'quarry', name:"Quarry", ic:'⛏️', cat:'Production', cost:{wood:30}, workers:2, requiresTech:'masonry',
   valid:(x,y)=>grid[y][x].terrain==='mountain', produce:{stone:2.2}},
 {id:'marblequarry', name:"Marble Quarry", ic:'🪨', cat:'Mining', cost:{wood:35,stone:25}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='marble', produce:{marble:1.8}, desc:'Extracts marble from mountain seams'},
 {id:'claypit', name:"Claypit", ic:'🕳️', cat:'Production', cost:{wood:20}, workers:2,
   valid:(x,y)=>grid[y][x].deposit==='clay', produce:{clay:2}},
 {id:'potter', name:"Potter", ic:'🏺', cat:'Production', cost:{wood:30,stone:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{clay:2}, produce:{pottery:1.6},
   desc:'Needs clay (from a Claypit) — produces pottery'},
 {id:'sawmill', name:"Woodcutter", ic:'🪓', cat:'Production', cost:{wood:20}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearTerrain(x,y,['forest'],1), produce:{wood:3}},
 {id:'beekeeper', name:"Beekeeper", ic:'🐝', cat:'Production', cost:{wood:25,stone:12}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearTerrain(x,y,['forest'],1), produce:{honey:1.4,wax:0.8},
   desc:'Keeps hives near woodland — produces honey and wax'},
 {id:'workshop', name:"Workshop", ic:'🔨', cat:'Production', cost:{wood:40,stone:20}, workers:3,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{wood:1.5,stone:1}, produce:{tools:1.6},
   desc:'Needs wood and stone — produces tools'},
 {id:'blacksmith', name:"Blacksmith", ic:'⚒️', cat:'Production', cost:{wood:30,stone:30}, workers:3, requiresTech:'metallurgy',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{copper:1,wood:1}, produce:{tools:2},
   desc:'Needs copper (from a Foundry) — produces tools'},
 {id:'foundry', name:"Foundry", ic:'🔥', cat:'Production', cost:{stone:50,wood:20}, workers:3,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain),
   special:'foundry', desc:'Refines ore from mines into gold, silver and copper'},
 {id:'hunterlodge', name:"Hunter's Lodge", ic:'🏹', cat:'Production', cost:{wood:25}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearTerrain(x,y,['forest'],1), produce:{deer:1.5}},
 {id:'docks', name:"Docks", ic:'⚓', cat:'Production', cost:{wood:40}, workers:2,
   valid:(x,y)=>grid[y][x].terrain==='sand' && nearTerrain(x,y,['sea','river'],1), produce:{fish:2}},
 {id:'boatbuilder', name:"Boat Builder", ic:'🛶', cat:'Production', cost:{wood:60,stone:20}, workers:3,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearBuilding(x,y,'docks',2),
   consume:{wood:5}, special:'boat'},
 {id:'goldmine', name:"Gold Mine", ic:'🟡', cat:'Mining', cost:{wood:40,stone:30}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='gold', produce:{goldOre:1.2}},
 {id:'silvermine', name:"Silver Mine", ic:'⚪', cat:'Mining', cost:{wood:40,stone:30}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='silver', produce:{silverOre:1.4}},
 {id:'coppermine', name:"Copper Mine", ic:'🟠', cat:'Mining', cost:{wood:40,stone:30}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='copper', produce:{copperOre:1.6}},
 {id:'tinmine', name:"Tin Mine", ic:'🧲', cat:'Mining', cost:{wood:40,stone:30}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='tin', produce:{tin:1.4}, desc:'Extracts tin ore from mountain seams'},
 {id:'saltmine', name:"Salt Flats", ic:'🧂', cat:'Mining', cost:{wood:35,stone:25}, workers:3,
   valid:(x,y)=>grid[y][x].deposit==='salt', produce:{salt:1.3}},
 {id:'mill', name:"Mill", ic:'⚙️', cat:'Production', cost:{wood:35,stone:15}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{wheat:2}, produce:{flour:1.6},
   desc:'Needs wheat (from a Field) — produces flour'},
 {id:'baker', name:"Baker", ic:'🍞', cat:'Production', cost:{wood:25,stone:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), special:'bakery',
   desc:'Needs flour (from a Mill) — bakes bread, and cakes if honey, jam, or cheese are in stock'},
 {id:'oliveoilmill', name:"Olive Press", ic:'🛢️', cat:'Production', cost:{wood:30,stone:15}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{olives:2}, produce:{oliveOil:1.4},
   desc:'Needs olives (from a Field planted with olives) — produces olive oil'},
 {id:'orchard', name:"Orchard", ic:'🍏', cat:'Production', cost:{wood:15}, workers:2, requiresTech:'orcharding',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{fruit:1.4},
   desc:'Grows fruit for the Baker and the Jam Maker'},
 {id:'jammaker', name:"Jam Maker", ic:'🫙', cat:'Production', cost:{wood:25,stone:10}, workers:2, requiresTech:'orcharding',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{fruit:1.5,sugarcane:1}, produce:{jam:1},
   desc:'Needs fruit (from an Orchard) and sugarcane (from a Field) — produces jam'},
 {id:'pigpasture', name:"Pig Pasture", ic:'🐖', cat:'Production', cost:{wood:25}, workers:2, requiresTech:'animalhusbandry',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{meat:1.0,hide:0.6},
   desc:'Raises pigs for meat and hide'},
 {id:'cowpasture', name:"Cow Pasture", ic:'🐄', cat:'Production', cost:{wood:30}, workers:2, requiresTech:'animalhusbandry',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{milk:1.4,meat:0.6,hide:0.5},
   desc:'Raises cattle for milk, meat, and hide'},
 {id:'goatpasture', name:"Goat Pasture", ic:'🐐', cat:'Production', cost:{wood:22}, workers:2, requiresTech:'animalhusbandry',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{milk:1.2,hide:0.5},
   desc:'Raises goats for milk and hide'},
 {id:'chickencoop', name:"Chicken Coop", ic:'🐔', cat:'Production', cost:{wood:18}, workers:1, requiresTech:'animalhusbandry',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{eggs:1.6,feathers:0.8,meat:0.4},
   desc:'Raises chickens for eggs, feathers, and meat'},
 {id:'butcher', name:"Butcher", ic:'🥩', cat:'Production', cost:{wood:30,stone:15}, workers:2, requiresTech:'animalhusbandry',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), produce:{meat:1.5},
   desc:'Processes livestock into extra meat'},
 {id:'tanner', name:"Tanner", ic:'🪢', cat:'Production', cost:{wood:25,stone:10}, workers:2, requiresTech:'tanning',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{hide:1.5}, produce:{leather:1},
   desc:'Needs hide (from pastures) — produces leather'},
 {id:'leatherworker', name:"Leatherworker", ic:'👜', cat:'Production', cost:{wood:30,stone:10}, workers:2, requiresTech:'tanning',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{leather:1.5}, produce:{leatherGoods:1},
   desc:'Needs leather (from a Tanner) — produces leather goods'},
 {id:'quiltmaker', name:"Quilt Maker", ic:'🛏️', cat:'Production', cost:{wood:25}, workers:2, requiresTech:'tanning',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{feathers:2}, produce:{quilts:0.8},
   desc:'Needs feathers (from Chicken Coops) — produces quilts and pillows'},
 {id:'dairy', name:"Dairy", ic:'🥛', cat:'Production', cost:{wood:30,stone:15}, workers:2, requiresTech:'dairyfarming',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), special:'dairy',
   desc:'Needs milk (from pastures) — churns butter, cheese, and cream'},
 {id:'candlemaker', name:"Candlemaker", ic:'🕯️', cat:'Production', cost:{wood:20,stone:10}, workers:2, requiresTech:'confectionery',
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{wax:1}, produce:{candles:1.2},
   desc:'Needs wax (from Beekeepers) — produces candles for Temples and trade'},
 {id:'stockage', name:"Storage Yard", ic:'📦', cat:'Storage', cost:{wood:50,stone:30}, workers:1,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), capBonus:{general:200}},
 {id:'granary', name:"Granary", ic:'🏛️', cat:'Storage', cost:{wood:40,stone:20}, workers:1,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), capBonus:{food:250}},
 {id:'road', name:"Road", ic:'🛤️', cat:'Infrastructure', cost:{stone:5}, workers:0,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain),
   desc:'Adjacent production buildings produce 15% more'},
 {id:'well', name:"Well", ic:'💧', cat:'Infrastructure', cost:{stone:15}, workers:1,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && nearTerrain(x,y,['river','sea'],3),
   happinessBonus:4, desc:'Irrigates nearby fields, +happiness'},
 {id:'sewer', name:"Sewer", ic:'♻️', cat:'Infrastructure', cost:{stone:25,tools:5}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain),
   happinessBonus:5, desc:'Softens disaster impact, +happiness'},
 {id:'police', name:"Police Post", ic:'🛡️', cat:'Services', cost:{wood:30,stone:20}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:6},
 {id:'fire', name:"Fire Post", ic:'🧯', cat:'Services', cost:{wood:30,stone:20}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:5},
 {id:'doctor', name:"Doctor's House", ic:'⚕️', cat:'Services', cost:{wood:30,stone:30}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:7},
 {id:'dentist', name:"Dentist", ic:'🦷', cat:'Services', cost:{wood:30,stone:20,tools:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:6},
 {id:'school', name:"School", ic:'🏫', cat:'Services', cost:{wood:40,stone:20}, workers:3,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:5,
   desc:'Boosts nearby Library research by 20%'},
 {id:'bar', name:"Bar", ic:'🍺', cat:'Services', cost:{wood:25,stone:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:8},
 {id:'temple', name:"Temple", ic:'⛩️', cat:'Services', cost:{stone:50,gold:6}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{candles:0.3}, happinessBonus:12,
   desc:'Burns candles (from a Candlemaker) to keep the shrine lit'},
 {id:'statue', name:"Statue", ic:'🗿', cat:'Services', cost:{marble:12,bronze:8,stone:10}, workers:1,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), happinessBonus:8,
   desc:'A civic monument built from marble and bronze'},
 {id:'scribe', name:"Scribe's House", ic:'✒️', cat:'Knowledge', cost:{wood:25,pottery:6}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain),
   consume:{pottery:0.6}, produce:{scrolls:1.2}, desc:'Needs pottery (from a Potter) — produces scrolls'},
 {id:'library', name:"Library", ic:'📚', cat:'Knowledge', cost:{wood:40,stone:20,tools:5}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain),
   consume:{scrolls:1}, special:'library', happinessBonus:4, desc:'Needs scrolls (from a Scribe\'s House) — converts them into research points'},
 {id:'market', name:"Market", ic:'🛒', cat:'Trade', cost:{wood:30,stone:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), special:'market'},
 {id:'tradingpost', name:"Trading Post", ic:'🐫', cat:'Trade', cost:{wood:50,stone:20,tools:5}, workers:3,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain) && (nearTerrain(x,y,['sea','river'],2)||true),
   special:'caravan', desc:'Buys and sells rare trade goods at a fixed exchange rate'},
 {id:'mint', name:"Mint", ic:'🪙', cat:'Trade', cost:{stone:40,tools:15}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), consume:{silver:1,copper:1}, special:'mint',
   desc:'Needs silver and copper (from a Foundry) — strikes coin directly'},
 {id:'taxoffice', name:"Tax Office", ic:'🏦', cat:'Trade', cost:{wood:40,stone:25}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), special:'taxoffice',
   desc:'Unlocks the Taxes panel'},
 {id:'barracks', name:"Barracks", ic:'🏹', cat:'Military', cost:{wood:40,stone:20,tools:10}, workers:2,
   valid:(x,y)=>['grass','sand'].includes(grid[y][x].terrain), militaryCap:6},
];

export const BLD_BY_ID = Object.fromEntries(BUILDINGS.map(b=>[b.id,b]));
export const CATS = ['Housing','Production','Mining','Infrastructure','Knowledge','Trade','Military','Storage','Services'];
